version: '3.3'

services:
  mysql:
    image: mysql:5.7
    volumes:
     - ./db_data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_DATABASE: "nest_boilerplate"
      MYSQL_USER: "nest_boilerplate"
      MYSQL_ROOT_PASSWORD: "p@ssw0rd"
      MYSQL_PASSWORD: "p@ssw0rd"
    ports:
      - "2318:3306"
  # nest:
  #   volumes:
  #    - ./dist:/usr/src/app/dist
  #   depends_on:
  #    - mysql
  #   build: .
  #   ports:
  #    - "700:3000"
  #   restart: always
